### ISSUE TITLE
IllegalStateException: Not on FX application thread

### ISSUE THREAD

**Issue by cbartzis** [finneyj/Racer#2]
As per a comment on a commit, I am also getting this error trying to run the Racer class directly from a fresh clone. This also happens on a custom class.
Machine specifications:
Windows 10
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
javac 1.8.0

Full error:
Exception in thread "main" java.lang.IllegalStateException: Not on FX application thread; currentThread = main
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
        at javafx.scene.Scene.<init>(Unknown Source)
        at javafx.scene.Scene.<init>(Unknown Source)
        at GameArena.<init>(GameArena.java:125)
        at Racer.<init>(Racer.java:55)
        at Racer.main(Racer.java:215)

Using Platform.runLater on the offending line seems to fix some things but breaks others.

**Comment by finneyj** [comment]
interesting... most builds seem happy with this, although it does sound like an this issue marvin raised on a recent pull request: https://github.com/finneyj/Racer/pull/1

Does this happen on a clean build of this repo, or only after you've made changes?

**Comment by cbartzis** [comment]
This happens on a clean build

**Comment by finneyj** [comment]
very curious, as this is find on most builds...

**Comment by cbartzis** [comment]
Update: I have updated to the latest version of Java and this seems to have fixed it. 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by finneyj** [comment]
ahh, cool. :-)

Just a bug in the JavaFX  code then. most likely just some validation that was a bit too strict. please close this issue off if you're happy.
